if(EXISTS "D:/Dev/1Project/Bee/build_test/Tests/Tensor/Tensor.Tests[1]_tests.cmake")
  include("D:/Dev/1Project/Bee/build_test/Tests/Tensor/Tensor.Tests[1]_tests.cmake")
else()
  add_test(Tensor.Tests_NOT_BUILT Tensor.Tests_NOT_BUILT)
endif()
