if(EXISTS "D:/Dev/1Project/Bee/build_test/Tests/Concurrency/Concurrency.Tests[1]_tests.cmake")
  include("D:/Dev/1Project/Bee/build_test/Tests/Concurrency/Concurrency.Tests[1]_tests.cmake")
else()
  add_test(Concurrency.Tests_NOT_BUILT Concurrency.Tests_NOT_BUILT)
endif()
